name: Merge PR
description: Squash‑merges a PR using the GitHub REST API.
author: Your Name

inputs:
  owner:
    description: Repository owner
    required: true
  repo:
    description: Repository name
    required: true
  number:
    description: Pull‑request number to merge
    required: true
  token:
    description: PAT (or GITHUB_TOKEN) with write access
    required: true

runs:
  using: "composite"
  steps:
    - name: Merge via gh api
      env:
        GH_TOKEN: ${{ inputs.token }}
        OWNER: ${{ inputs.owner }}
        REPO: ${{ inputs.repo }}
        PR_NUMBER: ${{ inputs.number }}
      shell: bash
      run: |
        gh api -X PUT \
          -H "Accept: application/vnd.github+json" \
          repos/${OWNER}/${REPO}/pulls/${PR_NUMBER}/merge \
          -f merge_method=squash \
          -f commit_title="chore(submods): squash merge #${PR_NUMBER}" \
          -f commit_message="Squash‑merged base PR after submodule merges."